pipeline {
    agent { label 'ec2' }
    tools {
      maven 'maven'
    }
    stages {
        stage('Source') {
            steps {
                sh 'mvn --version'
                sh 'git --version'
                git branch: 'main',
                    url: 'https://github.com/BANZOM/Jenkins-Practice.git'
            }
        }
        stage('Clean') {
            steps {
                dir("${env.WORKSPACE}/03/Jenkins-on-ssh-agent/hello"){
                    sh 'mvn clean'
                }
            }
        }
        stage('Test') {
            steps {
                dir("${env.WORKSPACE}/03/Jenkins-on-ssh-agent/hello"){
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                dir("${env.WORKSPACE}/03/Jenkins-on-ssh-agent/hello"){
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
}